README.md

boa atualização que fiz adicionando tópicos, com passar do tempo farei mais contribuições.

Links-Uteis atualizado

---

README.md

Adicionado:
- Linux
- Atom
- Se3Me Solutions
- p5.js

Adicinados links à zona de Open Source

---

README.md

Adicionar Debbugex, Designer.io e banco de ícones FlatIcon.

Adicionado ferramenta de RegEx e design

---

README.md

Incluindo Netlify nos links para hospedagem

Add Netlify

---

README.md

Boa noite. 
Inseri mais alguns links que acho interessante :D

Novos Links

---

README.md

Adicionardo BBEdit

---

README.md

Adicionado canal curso em vídeo, e o pessoal do PodTag

Adicionado Youtube / Podcast

---

README.md

App para criação e desenvolvimento de documentação para equipes ou para projetos individuais.

Inserido lucidchart link

---

README.md

- IDE Cloud: myCmpiler
- Canais no YouTube: Felipe Elia

Add sugestões em IDE Cloud e Canais do Youtube

---

README.md

* Novo podcast sobre Ciência de Dados
* Novo tutorial sobre WebCrawler

Adicionei um Podcast e um novo Tutorial Educacional

---

LINKS.md

Agora sim, alguns links que acho interessante adicionar.

Alguns links

---

LINKS.md

Achei um curso que não tem por aqui, olha só :1st_place_medal:

Adiciona link da Shellter Labs

---

README.md

com a âncora na imagem pode-se clicar tanto no link, quanto nela.

Para que a imagem também direcione para os links

---

LINKS.md

Foi adicionado links para ferramentas de compressão de imagens do formato PNG e JPG.
* [TinyPNG](https://tinypng.com/) 
* [TinyJPG](https://tinyjpg.com/) 
Foi adicionado link para a ferramenta que possibilita retirar a minificação e formatar o código CSS.
* [CSS Formatter](https://www.cleancss.com/css-beautify/)
Alguns bancos de imagens gratuitas.
* [StockSnap](https://stocksnap.io/)
* [Visual Hunt](https://visualhunt.com/)
Foi adicionado link para um game que ensina JavaScript.
* [Silent Teacher](http://silentteacher.toxicode.fr/) 
Foi adicionado link para IDE PyCharm, específica para a linguagem Python.
* [PyCharm](https://www.jetbrains.com/pycharm/)
Foi adicionado link para a ferramenta que permiti criar grid layout para o framework Bootstrap na versão 3 e 4.
* …

Adição de links

---

LINKS.md

Adiciona mais um canal do youtube

---

LINKS.md

- Incluindo Dart na categoria de Linguagens
- Incluindo Squoosh.app em Design Front-end

Incluindo Dart e Squoosh.app

---

LINKS.md

Adicionei alguns links para biblioteca de ícones, links para um site de visualização de palheta de cores e também adicionei alguns links para desafios

Adição de novos Links utéis

---

.gitignore
LINKS.md

Inserido alguns links nos seguintes Grupos.
* [Go](https://golang.org/) - A linguagem de programação Go é um projeto de código aberto para tornar os programadores mais produtivos.  
`O Go é expressivo, conciso, limpo e eficiente. Seus mecanismos de simultaneidade facilitam a gravação de programas que tiram o máximo proveito das máquinas multicore e em rede, enquanto seu novo sistema de tipos permite a construção de programas flexíveis e modulares. O Go compila rapidamente para o código da máquina, mas tem a conveniência da coleta de lixo e o poder da reflexão em tempo de execução. É uma linguagem compilada de forma estática e rápida que parece uma linguagem interpretada e de digitação dinâmica.`
* [Desafio333](https://github.com/codigofalado/desafio333) - O #Desafio333 é um desafio …

Inserido novos links em Linguagem de Programação, Desafios e Hosting.

---

LINKS.md

Adicionando banco de imagens e link para tutoriais .NET.

Adicionanado LINKS em diversas categorias

---

LINKS.md

Foram adicionados alguns links que utilizo de modo a contribuir com  o projeto.

Adicionado novos links em diversas categorias

---

LINKS.md

Adiciona o link para o comunidade do discord.

Adiciona link do Código Falado

---

LINKS.md

Adicionei o link para o site da Taiga.io (Gerenciador de projetos com equipes)

add taiga link

---

LINKS.md

Things: É um Gerenciador de Tarefas Pessoais.

Adicionei o Gerenciador de Tarefas - Things

---

LINKS.md

- adiciona o link da comunidade
- adiciona o link do grupo de estudos do CS50 brasileiro
- adiciona o link do canal do youtube

Adiciona Comunidade CodigoPraTodos

---

LINKS.md

1 - Adicionado DevChallenge como dica para desafios
2 - Adicionado Vercel como opção para hospedagem de sites

Adicionado DevChallenge e Vercel

---

LINKS.md

* Adiciona FontSpark -  ferramenta que ajuda encontrar rapidamente as melhores fontes para seus projetos. Gerar fontes de uma lista de fontes populares da web
* Adiciona Colors And Fonts - Ferramenta que lista diversas paletas de cores e tipografias

Adiciona FontSpark e ColorsAndFonts

---

LINKS.md

Adicionado links de eventos hackers e ferramentas de pentest em nuvem.

Adicionado links de CTFs e ferramentas de pentest

---

LINKS.md

Adicionado o canal do Daniel Donda.

new: canal do daniel donda

---

LINKS.md

Adicionando links de ferramentas de design e front-end.

new : adiciona ferramentas de frontend

---

LINKS.md

Retirei o ponto final da descrição

Consertando readme

---

LINKS.md

Adicionei um link de um editor de markdown online e free em ferramentas de desenvolvimento.

new: adiciona ferramenta de edição em markdown

---

LINKS.md

adiciona linguagem de programação elixir

new: adiciona linguagem de programação elixir

---

LINKS.md

Ordena os links dentro de cada categoria.

style: ordena os links alfabeticamente

---

ordena_md_categoria.py

Código em Python para a ordenação dos links.

new: adiciona código para ordenação dos links

---

LINKS.md

new: Adiciona 1 link de templates, freebies, tutoriais etc gratuitos de Bootstrap.

---

LINKS.md

**Índice** para melhorar a usabilidade da lista, facilitando a navegação pelo arquivo.

style: Adiciona indice para titulo das seçoes

---

LINKS.md

Uma plataforma que roda em cloud para programação na linguagem R, a ferramenta permite fazer a importação dos códigos direto do github, também permite salvar na github.
A linguagem R é bastante usada por profissionais que trabalham analise de dados, fortemente ligada aos estatísticos e cientistas da computação.

new: Nova IDE em Cloud para programaçaão na linguagem R

---

LINKS.md

https://devmind.io - Link quebrado

site offline - devmind

---

LINKS.md

Adicionei o Miro (https://miro.com/), que é um whiteboard colaborativo em real-time que pode ser usado de forma gratuita. É bem difundido atualmente e muitas pessoas utilizam, principalmente, para organizar processos de UX Design. Porém a ferramenta não se limita a isso, podendo organizar literalmente qualquer coisa (já que o usuário tem a liberdade de colocar o que quiser no whiteboard).

Adiciona o Miro à seção de Gerenciamento de Projetos

---

LINKS.md

Adicionei um link do IME-USP que há diversos materiais de estudos sobre análise de algoritmos.

new: adiciona link do IME-USP à seção de Estudos

---

LINKS.md

Olá pessoal, tudo bem?
Parabéns pelo conteúdo do repositório, está excelente.
Nesse PR, fiz a inclusão da ferramenta Azure DevOps, na seção de gerenciamento de projetos.
:)

Adiciona o Azure DevOps

---

LINKS.md

Boa noite!
Parabéns pelo excelente Repo, segue minha contribuição com um dos meus editores de código favorito

adiciona link editor de código neovim

---

LINKS.md

Alterações feitas : 
new : Adicionado link para a Linguagem R : https://cran.r-project.org/
new : Adicionado link para a IDE RStudio : https://www.rstudio.com/products/rstudio/download/#download

Links R e RStudio adicionados

---

LINKS.md

Adicionando [EasyForms](https://easyforms.vercel.app/).

new: Adicionando link EasyForms

---

LINKS.md

Site com projectos webs responsivos, front-end e full-stack, parecido com o devchallenge.com.br mas com projectos diferentes e interessantes para mim

new: adiciona novo link de desafios

---

LINKS.md

Foi adicionado Boss Level, um novo podcast de desenvolvimento na categoria Podcasts e Password Generator na categoria Ferramentas de desenvolvimento.

Adicioane Boss Level Podcast e Password Generator

---

LINKS.md

Foram adicionados 7 novos links de canais no **youtube** são eles:
- [Zero Bugs](https://www.youtube.com/c/ZeroBugs)
- [Vinícius Thiengo](https://www.youtube.com/c/ThiengoCalopsita/)
- [Guia do Programador](https://www.youtube.com/c/GuiadoProgramador)
- [Roger Melo](https://www.youtube.com/c/RogerMelo)
- [Programação Dinâmica](https://www.youtube.com/c/ProgramaçãoDinâmica)
- [One Bit Code](https://www.youtube.com/c/OneBitCode)
- [Erick Wendel](https://www.youtube.com/c/ErickWendelTreinamentos)

new: Adicionando novos links de canais no youtube

---

LINKS.md

Foi adicionado dois novos links na parte de estudo( IGTI e SoulCode )

 new: Adiciona IGTI e SoulCode em Estudos

---

LINKS.md

Adicionado PodApps Podcast, o primeiro podcast focado em privacidade no BR.

Adicionado meu podcast na aba de podcasts

---

LINKS.md

Atualiza da página de desafio (e também o url) de URI para Beecrowd

Atualiza LINKS.md

---

LINKS.md

<div align='center'>
</div>
Este projeto surgiu da ideia de ter um template de documentação simples mas robusto.
Esta documentação oferece suporte a tudo o que você deseja.
Não há limites. Ele foi construído no Next.js para que você possa colocar seus próprios componentes.
Ela oferece suporte à autenticação, Markdown, componentes react e Typescritpt. Você tem toda a liberdade para 
construir sua documentação da forma que imagina e ainda tem a velocidade de escrever em Markdown.
~~~bash
git clone https://github.com/NathanFirmo/next-docs.git
~~~
~~~bash
git clone git@github.com:NathanFirmo/next-docs.git
~~~
~~~bash
gh repo clone NathanFirmo/next-docs
~~~
~~~bash
npm i
yarn
~~~
Copie as informações do arquivo ***.env.sample*** para um arquivo ***.env***.
~~~bash
cp .env.sample .env
~~~ …

Adicionar link NextDocs

---

LINKS.md

Um site que uso bastante, ótimo site.

Novo link para site de hospedagem.

---

LINKS.md

Para ajustar ao padrão do documento o link foi reposicionado para o local apropriado

new: adicionando a ferramenta readmeso no setor de documentação

---

LINKS.md

API's públicas: https://github.com/public-apis/public-apis

new: adiciona repositório de API's públicas

---

LINKS.md
README.md

Fixed readme.md on the start browsing, the link wasn`t working

Fixed readme.md link
